layout_spectrum: 0.07811109861359
typography_spectrum: 0.39236273127608
color:
  brandStrength: 0.25427573709748685
  lightness: 0.5961405804846436
  saturation: 0.30054378183558583
  rhythmicContrast: 0.848089866572991
  brandColors:
    - '#7D8A2E'
    - '#C9D787'
    - '#FFFFFF'
    - '#FFC0A9'
    - '#FF8598'
name: Soul Training
title: Soul Training With Alicia Power
description: Make Your Way To Heaven!
